### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by michielree** [Smart123s/BeFake#2]
Many thanks for your continuing work on this project! Since last week I've run into an issue where I can't login anymore. I have tried all of the possible backends. Using the default `cloud` backend that I have alway used before, the request made at https://github.com/Smart123s/BeFake/blob/master/BeFake/BeFake.py#L217 receives the following response from the Identity Toolkit API:
```
{
  "error": {
    "code": 403,
    "message": "Requests from this Android client application \u003cempty\u003e are blocked.",
    "errors": [
      {
        "message": "Requests from this Android client application \u003cempty\u003e are blocked.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_ANDROID_APP_BLOCKED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "identitytoolkit.googleapis.com",
          "consumer": "projects/405768487586"
        }
      }
    ]
  }
}
```

**Comment by NicoWeio** [comment]
I just spent some time researching whether somebody has fixed this.
It seems like there has been another very recent update that broke basically everything.
I didn't keep track of all the issues and discussions I followed in the process, but I'll try to post here (and hopefully also create a PR) when the situation changes.
Feel free to ping me, should I forget.

Some pointers:
- > since october all requests sent a "bereal-signature" header with what appears to be a hash and now today it's being enforced. we don't know how they are generating the signature. If someone could reverse engineer the algorithm used than that's would be great but reading obfusicated code isn't very easy
- https://github.com/userbradley/BeReal/discussions/49
- https://github.com/macedonga/beunblurred/issues/16

**Comment by NicoWeio** [comment]
It's done (for now)! 🎉
I integrated the fix into my related fork (https://github.com/NicoWeio/BeFake/commit/a9fc1a154c4873e55d2ce57ca539087c1859dc13) and will try to create a PR.
Note that I haven't tested everything, only _login_ and _feed_.
In the long run, I guess it would make sense to combine this repo with my fork, but for now, let's just be happy we fixed it! :)

**Comment by Smart123s** [comment]
I've rebased my fork on [NicoWeio](https://github.com/NicoWeio)'s master branch. I would generally recommend using his for though, as he's more active with updates and bug fixes.
